services: docker

before_install:
  - docker -v
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

before_script:
  - docker-compose up -d --build
  - sleep 10

script:
  - docker-compose exec app python -m pytest tests

after_script:
  -docker-compose down
